# -*- coding: utf-8 -*-
"""BusinessIT2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wo-btT46a2TrluDId83pCCNf7H8J4Jcu
"""

import subprocess
subprocess.run(["pip", "install", "playwright"], check=True)
subprocess.run(["playwright", "install", "chromium"], check=True)
subprocess.run(["playwright", "install-deps", "chromium"], check=True)

import time
import os
import asyncio
import requests
from bs4 import BeautifulSoup
import pandas as pd
from supabase import create_client
from datetime import datetime
from playwright.async_api import async_playwright


URL = "https://directory.goodonyou.eco/categories/fashion/suits"
HEADERS = {"User-Agent": "Mozilla/5.0"}

LIMIT = 400
SLEEP_SECONDS = 0

SUPABASE_URL = os.environ["SUPABASE_URL"]
SUPABASE_KEY = os.environ["SUPABASE_KEY"]

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

scrape_time = datetime.now().isoformat()


async def fetch_rendered_html():
    async with async_playwright() as p:
        browser = await p.chromium.launch()
        page = await browser.new_page()
        await page.goto(URL, wait_until="networkidle")

        previous_height = 0
        while True:
            await page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
            await page.wait_for_timeout(1500)
            current_height = await page.evaluate("document.body.scrollHeight")
            if current_height == previous_height:
                break
            previous_height = current_height

        html = await page.content()
        await browser.close()
        return html


html = asyncio.run(fetch_rendered_html())
soup = BeautifulSoup(html, "html.parser")


def starts_with_rated(text):
    return text and text.startswith("Rated")


records = []
for link in soup.select('h5 a[href*="/brand/"]'):
    name = link.get_text(strip=True)
    card = link.parent.parent

    rating_span = card.find("span", string=starts_with_rated)
    if rating_span is None:
        rating, country = None, None
    else:
        rating = rating_span.get_text().replace("Rated :", "").strip()
        country_span = rating_span.find_next_sibling("span")
        country = country_span.get_text(strip=True) if country_span else None

    price_box = card.select_one('[class*="PriceRating"]')
    if price_box is None:
        price_raw = None
    else:
        price_raw = ""
        for span in price_box.find_all("span"):
            if "gray" not in span.get("style", ""):
                price_raw += "$"

    category_box = card.select_one('.hvnStw')
    category = category_box.get_text(separator=", ", strip=True) if category_box else None

    records.append({
        "name": name,
        "rating": rating,
        "country": country,
        "price_raw": price_raw,
        "category": category,
        "source_url": URL,
        "scraped_at": pd.Timestamp.now(tz="UTC").isoformat(),
    })

    if LIMIT and len(records) >= LIMIT:
        break

    time.sleep(SLEEP_SECONDS)

df = pd.DataFrame(records)


def price_to_number(price_raw):
    if not price_raw:
        return None
    return price_raw.count("$")


df["price"] = df["price_raw"].apply(price_to_number)

RATING_SCORES = {
    "Great": 5,
    "Good": 4,
    "It's a start": 3,
    "Not good enough": 2,
    "We avoid": 1,
}


def rating_to_score(rating):
    if not rating:
        return None
    return RATING_SCORES.get(rating)


df["rating_score"] = df["rating"].apply(rating_to_score)

df = df.dropna(subset=["price", "rating_score"])
df["price"] = df["price"].astype(int)
df["rating_score"] = df["rating_score"].astype(int)
df["scraped_at"] = pd.to_datetime(df["scraped_at"])

rows = []
for _, row in df.iterrows():
    rows.append({
        "name":         str(row["name"]),
        "rating":        str(row["rating"]),
        "country":       str(row["country"]),
        "price_raw":       str(row["price_raw"]),
        "category": str(row["category"]),
        "price_level": int(row["price"]),
        "rating_score":  int(row["rating_score"]),
        "source_url":    str(row["source_url"]),
        "scraped_at":    row["scraped_at"].isoformat(),
    })
# supabase.table("sustainabilityofsuits").delete().neq("name", "").execute()
result = supabase.table("sustainabilityofsuits").insert(rows).execute()
print(f"Inserted {len(rows)} rows into Supabase")

filename = "my_dataset.csv"

if os.path.exists(filename):
    # File already exists → append without writing headers again
    df.to_csv(filename, mode="a", header=False, index=False)
else:
    # First run → create file with headers
    df.to_csv(filename, index=False)

print(f"Appended {len(df)} rows — total file now has historical data")
